import type { Meta } from '@storybook/react'

const meta: Meta = {
  title: 'Stories/Atoms/Button',
  // tags: ['autodocs'],   ----> uncomment line to add autogenerated doc
  argTypes: {}
  // For argTypes doc, see https://storybook.js.org/docs/api/arg-types
}

export default meta
