const dotenv = require('dotenv')
dotenv.config()

const URL = process.env.COHORT360_URL_TEST
const LOGIN = process.env.COHORT360_LOGIN
const PASSWORD = process.env.COHORT360_PASSWORD

const HOME_PAGE_PATH = 'home'
const EXPLORE_PERIMETER_PAGE_PATH = 'perimeter'
const MY_PATIENTS_PAGE_PATH = 'my-patients'
const NEW_COHORT_PAGE_PATH = 'cohort/new'
const SAVED_COHORTS_PAGE_PATH = 'my-cohorts'
const SEARCH_PATIENT_PAGE_PATH = 'patient-search'
const PATIENT_DATAS_PAGE_PATH = 'my_patients/patients'
const PATIENT_DOCUMENTS_PAGE_PATH = 'my_patients/documents'
const PATIENT_DETAIL_PAGE_PATH = 'patients'
const EXPLORE_PERIMETER_PATIENT_DATAS_PAGE_PATH = 'perimeters/patients'
const MY_RESEARCH_PROJECTS_PAGE_PATH = 'my-requests'
// const _PAGE_PATH = ''

const MAX_LINE = 20
const NB_LINE = 3

const DEFAULT_ACCESS = '-'
const NOMINATIF_ACCESS = 'Nominatif'
const PSEUDONYMIZED_ACCESS = 'Pseudonymisé'

const PATIENT_GENDER_MALE_LIB = 'Hommes'
const PATIENT_GENDER_FEMALE_LIB = 'Femmes'
const PATIENT_GENDER_OTHER_LIB = 'Autres'
const PATIENT_GENDER_ALL_LIB = 'Tous les genres'
// const PATIENT_GENDER_FILTER_LIST = [ PATIENT_GENDER_MALE_LIB, PATIENT_GENDER_ALL_LIB, PATIENT_GENDER_OTHER_LIB, PATIENT_GENDER_FEMALE_LIB ]
const PATIENT_GENDER_FILTER_LIST = [ PATIENT_GENDER_MALE_LIB, PATIENT_GENDER_ALL_LIB, PATIENT_GENDER_FEMALE_LIB ]

const PATIENT_AGE_FILTER_AGE_MIN = 0
const PATIENT_AGE_FILTER_AGE_MAX = 130
const PATIENT_AGE_FILTER_LIST = [ [5, 40], [45, 110], [30, 90] ]

const PATIENT_VITAL_STATUS_ALIVE_LIB = 'Patients vivants'
const PATIENT_VITAL_STATUS_DEAD_LIB = 'Patients décédés'
const PATIENT_VITAL_STATUS_ALL_LIB = 'Tous les patients'
const PATIENT_VITAL_STATUS_FILTER_LIST = [ PATIENT_VITAL_STATUS_DEAD_LIB, PATIENT_VITAL_STATUS_ALL_LIB, PATIENT_VITAL_STATUS_ALIVE_LIB ]

const PATIENT_SEARCH_IPP_LIB = 'IPP'
const PATIENT_SEARCH_FIRST_NAME_LIB = 'Prénom'
const PATIENT_SEARCH_LAST_NAME_LIB = 'Nom'
const PATIENT_SEARCH_ALL_LIB = 'Tous les champs'
// const PATIENT_SEARCH_FILTER_LIST = [ [PATIENT_SEARCH_IPP_LIB, ''], [PATIENT_SEARCH_ALL_LIB, 'martin'], [PATIENT_SEARCH_FIRST_NAME_LIB, 'jean'], [PATIENT_SEARCH_FIRST_NAME_LIB, 'louis'], [PATIENT_SEARCH_FIRST_NAME_LIB, 'marie'], [PATIENT_SEARCH_LAST_NAME_LIB, 'martin'] ]
const PATIENT_SEARCH_FILTER_LIST = [ [PATIENT_SEARCH_IPP_LIB, ''], [PATIENT_SEARCH_ALL_LIB, 'martin'], [PATIENT_SEARCH_LAST_NAME_LIB, 'martin'], [PATIENT_SEARCH_FIRST_NAME_LIB, 'marie']  ]


const DOCUMENT_DATE_FILTER_INTERVAL_LIST = [ ['21/06/2016', '21/06/2017'], ['01/01/2020', '31/12/2020'] ]
const DOCUMENT_TYPE_FILTER_TYPE_LIST = [ ['CR de Jour', 'HDJ'], ['CR Consultation', 'CR Consultation'] ]
const DOCUMENT_SEARCH_FILTER_LIST = [ 'embolie', 'pulmonaire', 'embolie pulmonaire', 'embolie AND pulmonaire', 'embolie NOT pulmonaire', '"embolie pulmonaire"' ]

const DOCUMENT_SORT_DATE_LIB = 'Date'
const DOCUMENT_SORT_TYPE_LIB = 'Type de document'
const DOCUMENT_SORT_FILTER_LIST = [ DOCUMENT_SORT_TYPE_LIB, DOCUMENT_SORT_DATE_LIB ]

const REQUEST_SEARCH_PROJECT_TEST_LIB = '_TestProject_' + new Date().getFullYear() + '' + ((new Date().getMonth() + 1) < 10 ? '0' + (new Date().getMonth() + 1) : new Date().getMonth() + 1) + '' +  (new Date().getDate() < 10 ? '0' + new Date().getDate() : new Date().getDate())
const REQUEST_REQUEST_TEST_LIB = '_TestRequest_' + new Date().getFullYear() + '' + ((new Date().getMonth() + 1) < 10 ? '0' + (new Date().getMonth() + 1) : new Date().getMonth() + 1) + '' +  (new Date().getDate() < 10 ? '0' + new Date().getDate() : new Date().getDate())

exports.URL = URL
exports.LOGIN = LOGIN
exports.PASSWORD = PASSWORD
exports.HOME_PAGE_PATH = HOME_PAGE_PATH
exports.EXPLORE_PERIMETER_PAGE_PATH = EXPLORE_PERIMETER_PAGE_PATH
exports.MY_PATIENTS_PAGE_PATH = MY_PATIENTS_PAGE_PATH
exports.NEW_COHORT_PAGE_PATH = NEW_COHORT_PAGE_PATH
exports.SAVED_COHORTS_PAGE_PATH = SAVED_COHORTS_PAGE_PATH
exports.SEARCH_PATIENT_PAGE_PATH = SEARCH_PATIENT_PAGE_PATH
exports.PATIENT_DATAS_PAGE_PATH = PATIENT_DATAS_PAGE_PATH
exports.PATIENT_DOCUMENTS_PAGE_PATH = PATIENT_DOCUMENTS_PAGE_PATH
exports.PATIENT_DETAIL_PAGE_PATH = PATIENT_DETAIL_PAGE_PATH
exports.EXPLORE_PERIMETER_PATIENT_DATAS_PAGE_PATH = EXPLORE_PERIMETER_PATIENT_DATAS_PAGE_PATH
exports.MY_RESEARCH_PROJECTS_PAGE_PATH = MY_RESEARCH_PROJECTS_PAGE_PATH

exports.MAX_LINE = MAX_LINE
exports.NB_LINE = NB_LINE

exports.DEFAULT_ACCESS = DEFAULT_ACCESS
exports.NOMINATIF_ACCESS = NOMINATIF_ACCESS
exports.PSEUDONYMIZED_ACCESS = PSEUDONYMIZED_ACCESS

exports.PATIENT_GENDER_MALE_LIB = PATIENT_GENDER_MALE_LIB
exports.PATIENT_GENDER_FEMALE_LIB = PATIENT_GENDER_FEMALE_LIB
exports.PATIENT_GENDER_OTHER_LIB = PATIENT_GENDER_OTHER_LIB
exports.PATIENT_GENDER_ALL_LIB = PATIENT_GENDER_ALL_LIB
exports.PATIENT_GENDER_FILTER_LIST = PATIENT_GENDER_FILTER_LIST

exports.PATIENT_AGE_FILTER_AGE_MIN = PATIENT_AGE_FILTER_AGE_MIN
exports.PATIENT_AGE_FILTER_AGE_MAX = PATIENT_AGE_FILTER_AGE_MAX
exports.PATIENT_AGE_FILTER_LIST = PATIENT_AGE_FILTER_LIST

exports.PATIENT_VITAL_STATUS_ALIVE_LIB = PATIENT_VITAL_STATUS_ALIVE_LIB
exports.PATIENT_VITAL_STATUS_DEAD_LIB = PATIENT_VITAL_STATUS_DEAD_LIB
exports.PATIENT_VITAL_STATUS_ALL_LIB = PATIENT_VITAL_STATUS_ALL_LIB
exports.PATIENT_VITAL_STATUS_FILTER_LIST = PATIENT_VITAL_STATUS_FILTER_LIST

exports.PATIENT_SEARCH_IPP_LIB = PATIENT_SEARCH_IPP_LIB
exports.PATIENT_SEARCH_FIRST_NAME_LIB = PATIENT_SEARCH_FIRST_NAME_LIB
exports.PATIENT_SEARCH_LAST_NAME_LIB = PATIENT_SEARCH_LAST_NAME_LIB
exports.PATIENT_SEARCH_ALL_LIB = PATIENT_SEARCH_ALL_LIB
exports.PATIENT_SEARCH_FILTER_LIST = PATIENT_SEARCH_FILTER_LIST

exports.DOCUMENT_DATE_FILTER_INTERVAL_LIST = DOCUMENT_DATE_FILTER_INTERVAL_LIST
exports.DOCUMENT_TYPE_FILTER_TYPE_LIST = DOCUMENT_TYPE_FILTER_TYPE_LIST
exports.DOCUMENT_SEARCH_FILTER_LIST = DOCUMENT_SEARCH_FILTER_LIST

exports.DOCUMENT_SORT_DATE_LIB = DOCUMENT_SORT_DATE_LIB
exports.DOCUMENT_SORT_TYPE_LIB = DOCUMENT_SORT_TYPE_LIB
exports.DOCUMENT_SORT_FILTER_LIST = DOCUMENT_SORT_FILTER_LIST

exports.REQUEST_SEARCH_PROJECT_TEST_LIB = REQUEST_SEARCH_PROJECT_TEST_LIB
exports.REQUEST_REQUEST_TEST_LIB = REQUEST_REQUEST_TEST_LIB
