import React from 'react'
import { Button } from './Button'
import type { Meta, StoryObj } from '@storybook/react'

const meta: Meta<typeof Button> = {
  title: 'Stories/Atoms/Button',
  component: Button,
  // tags: ['autodocs'],   ----> uncomment line to add autogenerated doc
  argTypes: {
    disabled: {
      description: `Is the button disabled?`,
      table: { defaultValue: { summary: 'false' } }
    },
    variant: {
      options: ['text', 'contained', 'outlined'],
      control: 'inline-radio',
      table: { defaultValue: { summary: 'contained' } }
    },
    size: {
      description: `How large should the button be?`,
      options: ['small', 'medium', 'large'],
      control: 'inline-radio',
      table: {
        type: { summary: `'small' | 'medium' | 'large'` },
        defaultValue: { summary: 'medium' }
      }
    },
    children: {
      description: 'Your button text',
      name: 'label',
      control: 'text',
      table: { defaultValue: { summary: '' } }
    },
    ref: { if: { arg: 'parent', exists: true } },
    component: { if: { arg: 'parent', exists: true } }
  },
  // For argTypes doc, see https://storybook.js.org/docs/api/arg-types
  decorators: [
    (Story) => (
      <div style={{ margin: '40px' }}>
        <Story />
      </div>
    )
  ]
}

export default meta

type Story = StoryObj<typeof Button>

// More on writing stories with args: https://storybook.js.org/docs/react/writing-stories/args
export const Playground: Story = {
  args: {
    disabled: false,
    href: '',
    children: 'Button',
    size: 'medium',
    variant: 'contained'
  }
}
